name: 'Deploy to Firebase Hosting by target name'
author: 'Tommy Kim <tomket2@naver.com>'
description: 'A GitHub Action to deploy to Firebase Hosting by target name'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'red'